### PR TITLE
Appsetup

### PR DESCRIPTION
**Pull request by sedroche**

### CODE REVIEW

**Comment by aidenkeating** [comment]
👀

**Comment by sedroche** [comment]
@ciaranRoche Yeah separating by components I think. Whatever makes sense be it a feature or component. Probably a `/common` too

**Comment by wei-lee** [comment]
@sedroche Unfortunately, due to security reasons, this project on CircleCI won't build PRs from forks. We will have to create PRs from the upstream repo for now.

**Comment by sedroche** [comment]
@wei-lee Ok thanks. I will recreate it

**Comment by sedroche** [comment]
closing for https://github.com/aerogear/mobile-client-service/pull/9 (https://github.com/aerogear/mobile-client-service/pull/6#issuecomment-407197010)

**Pull request closed without merging**
