### PR TITLE
Added progress bars for builds

### PR DESCRIPTION
**Pull request by jhellar**
# Motivation

https://issues.jboss.org/browse/AEROGEAR-7946

# Verification steps

1. deploy local OpenShift with mobile-core
2. provision mobile CI/CD service
3. create mobile client
4. open mobile client's details and navigate to builds tab
5. create new build configuration (you can use https://github.com/aerogear/cordova-showcase-template.git)
6. fetch and checkout this PR
7. `make serve`
8. in OpenShift console start new build
9. open `localhost:4000` in your browser
10. open the mobile app and navigate to builds tab
11. expand build config
12. you should see progress bars showing stages of the build
13. refresh page to watch build progress

### CODE REVIEW

**Comment by psturc** [comment]
👀

**Comment by jhellar** [comment]
@psturc thanks for review. Should be fixed now.

**Comment by psturc** [comment]
@jhellar I verified the fix and no longer seeing the error.

Just a tiny thing: if no stages have started in the build, please add the info message (as displayed in OpenShift console):

screen shot 2018-09-27 at 11 11 51

**Comment by jhellar** [comment]
@psturc should be fixed now.

**Comment by psturc** [comment]
@jhellar let's rebase and merge this guy

**Pull request merged**
